### ISSUE TITLE
Is the sqlx fork still needed?

### ISSUE THREAD

**Issue by brandonros** [dimfeld/ergo#30]
https://github.com/dimfeld/sqlx/commit/263ae9918b9b14c355b5ff0b0c0c2503d7cc3ae5

**Comment by dimfeld** [comment]
No, shouldn't be needed anymore. I'm planning to drop it and move over to latest sqlx 0.6 whenever I get back to working on this project again. If normal 0.6 doesn't work right now then 0.5 should.
